version: "3.9"
services:
  jupyter:
    build: .
    ports:
      - "10000:8888"
    volumes:
      - .:/home/jovyan
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: